name             'mongo_chef_gem'
maintainer       'Andrei Skopenko'
maintainer_email 'andrey@skopenko.net'
license          'Apache-2.0'
description      'Provides the mongo_chef_gem resource'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url 'https://github.com/scopenco/chef-mongo_chef_gem'
issues_url 'https://github.com/scopenco/chef-mongo_chef_gem/issues'
version '0.2.2'

supports 'amazon'
supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'fedora'
supports 'debian'
supports 'ubuntu'
